// Mock data for My Content page

export interface Article {
  id: string;
  title: string;
  content: string;
  excerpt: string;
  status: "draft" | "published";
  wordCount: number;
  readingTime: number;
  createdAt: string;
  updatedAt: string;
  keywords: string[];
  thumbnail?: string;
  seoScore?: number;
  category: string;
}

export const mockArticles: Article[] = [
  {
    id: "1",
    title: "10 Proven Strategies to Boost Your SEO Rankings in 2024",
    excerpt: "Learn the latest SEO techniques that are actually working in 2024. From technical optimization to content strategies...",
    content: "# 10 Proven Strategies to Boost Your SEO Rankings in 2024\n\nSEO is constantly evolving...",
    status: "published",
    wordCount: 2450,
    readingTime: 12,
    createdAt: "2024-01-10T10:30:00Z",
    updatedAt: "2024-01-10T14:20:00Z",
    keywords: ["SEO", "Rankings", "Search Engine", "Optimization"],
    seoScore: 92,
    category: "SEO",
  },
  {
    id: "2",
    title: "The Ultimate Guide to Content Marketing for Beginners",
    excerpt: "A comprehensive introduction to content marketing, covering strategy, creation, distribution, and measurement...",
    content: "# The Ultimate Guide to Content Marketing for Beginners\n\nContent marketing has become essential...",
    status: "published",
    wordCount: 3200,
    readingTime: 16,
    createdAt: "2024-01-09T09:15:00Z",
    updatedAt: "2024-01-09T11:45:00Z",
    keywords: ["Content Marketing", "Marketing Strategy", "Beginners Guide"],
    seoScore: 88,
    category: "Marketing",
  },
  {
    id: "3",
    title: "How AI is Transforming the Future of Content Creation",
    excerpt: "Explore how artificial intelligence is revolutionizing content creation, from writing to design and beyond...",
    content: "# How AI is Transforming the Future of Content Creation\n\nArtificial intelligence is reshaping...",
    status: "draft",
    wordCount: 1850,
    readingTime: 9,
    createdAt: "2024-01-08T16:00:00Z",
    updatedAt: "2024-01-08T17:30:00Z",
    keywords: ["AI", "Content Creation", "Artificial Intelligence", "Future"],
    seoScore: 85,
    category: "Technology",
  },
  {
    id: "4",
    title: "Social Media Marketing Tips That Actually Work",
    excerpt: "Discover proven social media marketing strategies that drive real engagement and conversions...",
    content: "# Social Media Marketing Tips That Actually Work\n\nSocial media marketing can be overwhelming...",
    status: "published",
    wordCount: 1950,
    readingTime: 10,
    createdAt: "2024-01-07T13:20:00Z",
    updatedAt: "2024-01-07T15:10:00Z",
    keywords: ["Social Media", "Marketing", "Engagement", "Strategy"],
    seoScore: 90,
    category: "Social Media",
  },
  {
    id: "5",
    title: "Building a Successful Blog: From Zero to Hero",
    excerpt: "A step-by-step guide to starting and growing a successful blog, from choosing a niche to monetization...",
    content: "# Building a Successful Blog: From Zero to Hero\n\nStarting a blog is exciting...",
    status: "draft",
    wordCount: 2750,
    readingTime: 14,
    createdAt: "2024-01-06T11:45:00Z",
    updatedAt: "2024-01-06T14:30:00Z",
    keywords: ["Blogging", "Blog", "Content Strategy", "Monetization"],
    seoScore: 82,
    category: "Blogging",
  },
  {
    id: "6",
    title: "Email Marketing Best Practices for 2024",
    excerpt: "Master email marketing with these proven best practices for improving open rates, click-through rates, and conversions...",
    content: "# Email Marketing Best Practices for 2024\n\nEmail marketing remains one of the most...",
    status: "published",
    wordCount: 2100,
    readingTime: 11,
    createdAt: "2024-01-05T10:00:00Z",
    updatedAt: "2024-01-05T12:15:00Z",
    keywords: ["Email Marketing", "Best Practices", "Conversion", "Engagement"],
    seoScore: 87,
    category: "Email Marketing",
  },
  {
    id: "7",
    title: "The Complete Guide to Google Analytics 4",
    excerpt: "Everything you need to know about Google Analytics 4, from setup to advanced reporting and insights...",
    content: "# The Complete Guide to Google Analytics 4\n\nGoogle Analytics 4 represents a major shift...",
    status: "draft",
    wordCount: 3500,
    readingTime: 18,
    createdAt: "2024-01-04T14:30:00Z",
    updatedAt: "2024-01-04T16:45:00Z",
    keywords: ["Google Analytics", "GA4", "Analytics", "Tracking"],
    seoScore: 91,
    category: "Analytics",
  },
  {
    id: "8",
    title: "How to Create Viral Content on Social Media",
    excerpt: "Learn the secrets behind viral content and how to increase your chances of creating posts that spread...",
    content: "# How to Create Viral Content on Social Media\n\nCreating viral content is part science...",
    status: "published",
    wordCount: 1650,
    readingTime: 8,
    createdAt: "2024-01-03T09:20:00Z",
    updatedAt: "2024-01-03T11:00:00Z",
    keywords: ["Viral Content", "Social Media", "Content Strategy"],
    seoScore: 84,
    category: "Social Media",
  },
  {
    id: "9",
    title: "WordPress SEO: The Definitive Guide",
    excerpt: "Optimize your WordPress site for search engines with this comprehensive guide to WordPress SEO...",
    content: "# WordPress SEO: The Definitive Guide\n\nWordPress powers over 40% of websites...",
    status: "published",
    wordCount: 2900,
    readingTime: 15,
    createdAt: "2024-01-02T11:00:00Z",
    updatedAt: "2024-01-02T13:30:00Z",
    keywords: ["WordPress", "SEO", "Website Optimization", "CMS"],
    seoScore: 93,
    category: "SEO",
  },
  {
    id: "10",
    title: "Understanding Your Target Audience: A Data-Driven Approach",
    excerpt: "Use data and analytics to deeply understand your target audience and create content that resonates...",
    content: "# Understanding Your Target Audience: A Data-Driven Approach\n\nKnowing your audience is crucial...",
    status: "draft",
    wordCount: 2200,
    readingTime: 11,
    createdAt: "2024-01-01T10:15:00Z",
    updatedAt: "2024-01-01T12:00:00Z",
    keywords: ["Target Audience", "Data Analysis", "Marketing"],
    seoScore: 86,
    category: "Marketing",
  },
  {
    id: "11",
    title: "Video Marketing Trends to Watch in 2024",
    excerpt: "Stay ahead of the curve with these emerging video marketing trends that will shape the industry in 2024...",
    content: "# Video Marketing Trends to Watch in 2024\n\nVideo content continues to dominate...",
    status: "published",
    wordCount: 1800,
    readingTime: 9,
    createdAt: "2023-12-30T14:00:00Z",
    updatedAt: "2023-12-30T15:45:00Z",
    keywords: ["Video Marketing", "Trends", "Video Content"],
    seoScore: 89,
    category: "Video Marketing",
  },
  {
    id: "12",
    title: "The Art of Storytelling in Content Marketing",
    excerpt: "Master the art of storytelling to create compelling content that connects with your audience emotionally...",
    content: "# The Art of Storytelling in Content Marketing\n\nStories have been used for thousands...",
    status: "draft",
    wordCount: 2350,
    readingTime: 12,
    createdAt: "2023-12-29T09:30:00Z",
    updatedAt: "2023-12-29T11:15:00Z",
    keywords: ["Storytelling", "Content Marketing", "Narrative"],
    seoScore: 81,
    category: "Content Strategy",
  },
  {
    id: "13",
    title: "Local SEO: How to Rank in Local Search Results",
    excerpt: "Dominate local search results with these proven local SEO strategies for businesses of all sizes...",
    content: "# Local SEO: How to Rank in Local Search Results\n\nLocal SEO is critical for businesses...",
    status: "published",
    wordCount: 2650,
    readingTime: 13,
    createdAt: "2023-12-28T13:45:00Z",
    updatedAt: "2023-12-28T15:30:00Z",
    keywords: ["Local SEO", "Local Search", "Google My Business"],
    seoScore: 94,
    category: "SEO",
  },
  {
    id: "14",
    title: "Influencer Marketing: A Complete Guide",
    excerpt: "Everything you need to know about influencer marketing, from finding the right influencers to measuring ROI...",
    content: "# Influencer Marketing: A Complete Guide\n\nInfluencer marketing has exploded...",
    status: "draft",
    wordCount: 3100,
    readingTime: 16,
    createdAt: "2023-12-27T10:20:00Z",
    updatedAt: "2023-12-27T12:45:00Z",
    keywords: ["Influencer Marketing", "Influencers", "Social Media"],
    seoScore: 83,
    category: "Marketing",
  },
  {
    id: "15",
    title: "Content Repurposing: Get More From Your Content",
    excerpt: "Maximize your content ROI by repurposing your best content across multiple channels and formats...",
    content: "# Content Repurposing: Get More From Your Content\n\nCreating great content takes time...",
    status: "published",
    wordCount: 1700,
    readingTime: 9,
    createdAt: "2023-12-26T11:30:00Z",
    updatedAt: "2023-12-26T13:00:00Z",
    keywords: ["Content Repurposing", "Content Strategy", "ROI"],
    seoScore: 88,
    category: "Content Strategy",
  },
  {
    id: "16",
    title: "Mobile-First Indexing: What You Need to Know",
    excerpt: "Understand Google's mobile-first indexing and how to optimize your website for mobile search...",
    content: "# Mobile-First Indexing: What You Need to Know\n\nGoogle now uses mobile-first indexing...",
    status: "published",
    wordCount: 2000,
    readingTime: 10,
    createdAt: "2023-12-25T09:00:00Z",
    updatedAt: "2023-12-25T10:45:00Z",
    keywords: ["Mobile SEO", "Mobile-First", "Google", "Indexing"],
    seoScore: 90,
    category: "SEO",
  },
  {
    id: "17",
    title: "The Psychology of Color in Marketing",
    excerpt: "Discover how color psychology affects consumer behavior and how to use it in your marketing strategy...",
    content: "# The Psychology of Color in Marketing\n\nColor plays a powerful role...",
    status: "draft",
    wordCount: 1550,
    readingTime: 8,
    createdAt: "2023-12-24T15:15:00Z",
    updatedAt: "2023-12-24T16:30:00Z",
    keywords: ["Color Psychology", "Marketing", "Branding"],
    seoScore: 79,
    category: "Marketing",
  },
  {
    id: "18",
    title: "Conversion Rate Optimization: The Ultimate Guide",
    excerpt: "Learn how to optimize your conversion rates with proven CRO strategies and techniques...",
    content: "# Conversion Rate Optimization: The Ultimate Guide\n\nConversion rate optimization (CRO)...",
    status: "published",
    wordCount: 3300,
    readingTime: 17,
    createdAt: "2023-12-23T10:45:00Z",
    updatedAt: "2023-12-23T13:15:00Z",
    keywords: ["CRO", "Conversion Rate", "Optimization", "Testing"],
    seoScore: 92,
    category: "Conversion",
  },
];

export const mockContentStats = {
  total: mockArticles.length,
  drafts: mockArticles.filter((a) => a.status === "draft").length,
  published: mockArticles.filter((a) => a.status === "published").length,
  totalWords: mockArticles.reduce((sum, a) => sum + a.wordCount, 0),
};

export const categories = Array.from(
  new Set(mockArticles.map((a) => a.category))
).sort();

export const allKeywords = Array.from(
  new Set(mockArticles.flatMap((a) => a.keywords))
).sort();
