'use client';

import { useState } from 'react';

const faqs = [
  {
    question: 'How does the AI generate content?',
    answer:
      'ContentGen uses advanced large language models trained on millions of high-quality articles. Our AI analyzes your input, understands context and intent, then generates original content that matches your specifications. The system is continuously learning and improving to deliver better results.',
  },
  {
    question: 'Is the content plagiarism-free?',
    answer:
      'Yes, absolutely. All content generated by ContentGen is 100% original. Our AI creates new content from scratch based on patterns learned from training data—it doesn\'t copy or paraphrase existing articles. Every piece passes plagiarism detection tools with flying colors.',
  },
  {
    question: 'Can I edit the generated content?',
    answer:
      'Of course! ContentGen includes a full-featured editor where you can refine, rewrite, or expand any part of the generated content. You can also regenerate specific sections, adjust tone, or add your own insights. Think of it as a collaborative writing partner.',
  },
  {
    question: 'What languages are supported?',
    answer:
      'ContentGen supports 25+ languages including English, Spanish, French, German, Italian, Portuguese, Dutch, Russian, Chinese (Simplified & Traditional), Japanese, Korean, Arabic, Hindi, and many more. Content quality is consistently high across all supported languages.',
  },
  {
    question: 'Do you offer refunds?',
    answer:
      'Yes, we offer a 30-day money-back guarantee. If you\'re not satisfied with ContentGen for any reason within the first 30 days, simply contact our support team and we\'ll issue a full refund—no questions asked. We also offer a 14-day free trial so you can try before you buy.',
  },
  {
    question: 'Can I cancel my subscription anytime?',
    answer:
      'Absolutely. There are no long-term contracts or commitments. You can cancel your subscription at any time from your account settings. If you cancel, you\'ll retain access until the end of your current billing period.',
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section
      id="faq"
      className="px-6 md:px-12 py-[60px] md:py-[100px] bg-[#fafafa]"
    >
      <div className="max-w-[900px] mx-auto">
        {/* Section Badge */}
        <div className="inline-flex items-center gap-2 px-4 py-[6px] mb-6 bg-white border border-[#e5e5e5] rounded-[20px]">
          <span className="text-[13px] font-medium text-[#404040]">❓ FAQ</span>
        </div>

        {/* Section Heading */}
        <h2 className="text-[36px] md:text-[48px] font-bold text-[#171717] leading-[1.2] tracking-[-0.02em] mb-12 font-satoshi">
          Frequently asked questions
        </h2>

        {/* FAQ Accordion */}
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="bg-white border border-[#e5e5e5] rounded-xl overflow-hidden"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-[#fafafa] transition-colors duration-200"
                aria-expanded={openIndex === index}
              >
                <span className="text-base font-semibold text-[#171717] font-inter">
                  {faq.question}
                </span>
                <svg
                  className={`w-5 h-5 text-[#404040] transition-transform duration-200 ${
                    openIndex === index ? 'rotate-180' : ''
                  }`}
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  viewBox="0 0 24 24"
                >
                  <polyline points="6 9 12 15 18 9"></polyline>
                </svg>
              </button>
              {openIndex === index && (
                <div className="px-6 pb-5">
                  <p className="text-sm text-[#737373] leading-[1.6]">
                    {faq.answer}
                  </p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
